### ISSUE TITLE
Support for php 8.1?

### ISSUE THREAD

**Issue by garak** [phpstan/phpstan-phpunit#138]
I just raised the requirements in a library of mine to support PHP ^8.1 and I can't make this library work.
As you can see in [this action](https://github.com/dustin10/VichUploaderBundle/runs/7940957740?check_suite_focus=true), even if the plugin is enabled, I'm getting phpstan errors like "Return type of call to method PHPUnit\Framework\TestCase::createMock() contains unresolvable type". The version of phpstan-phpunit is 1.1.1 and the version of phpstan is 1.8.2

Moreover, I see that the README here is a bit outdated, showing only examples that use phpdoc (no typed properties or returns) and old, non-namespaced, classes of phpunit.

**Comment by ondrejmirtes** [comment]
This has nothing to do with PHP 8.1. The reason why "contains unresolvable type" is because your classes are marked with `@final`, and final classes cannot be mocked by PHPUnit. I know this is just a PHPDoc tag, and doesn't influence the ability to mock classes, but PHPStan considers both `@final` and `final class` to be the same.

I could change the logic to only look at `final class`, but my worry is that it'd hamper some other scenario.

> Moreover, I see that the README here is a bit outdated

Feel free to submit a PR!

**Comment by garak** [comment]
So even if you use dg/bypass-finals it won't work? Do you think there could be a way to support that?

**Comment by ondrejmirtes** [comment]
Oh, PHPStan is actually right here, it's not about `@final` but `final class` really that's part of your PR changes. I realized that when I wasn't able to reproduce the issue on phpstan.org/try.

dg/bypass-finals might help here, but that's an ugly hack. You shouldn't really mock final class here, use interfaces instead.
