### ISSUE TITLE
Regression with assertEmpty extension

### ISSUE THREAD

**Issue by Seldaek** [phpstan/phpstan-phpunit#141]
Somehow passing `array<'0.6.0'|'1.0.0'|'1.0.x-dev'|'1.1.x-dev'|'9999999-dev'|'dev-feature-b'|'dev-feature/a-1.0-B'|'dev-master', true>` into `self::assertEmpty()` is not allowed

```
183    Call to method PHPUnit\Framework\Assert::assertEmpty() with
         array<'0.6.0'|'1.0.0'|'1.0.x-dev'|'1.1.x-dev'|'9999999-dev'|'dev-feature-b'|'dev-feature/a-1.0-B'|'dev-master', true> and
         literal-string&non-falsy-string will always evaluate to false.
```

It's not a non-empty-array, so I don't see why it isn't allowed.

The code looks something like this, but obviously there is no error there as I cannot use the phpunit code

https://phpstan.org/r/7c7be20e-ed51-4311-a0e0-74c061f99561

**Comment by ondrejmirtes** [comment]
I can't reproduce it :( https://github.com/phpstan/phpstan-phpunit/commit/f92aab7b75ebbcc5b59b012de1b12cadf5286b6f

**Comment by Seldaek** [comment]
You can check with composer if you remove https://github.com/composer/composer/commit/923ff98ea06ee9d9d886ef8de052bf4c9ce8cc26 from the baseline

**Comment by knallcharge** [comment]
I have a similar problem since the last update, removing "phpstan/phpstan-phpunit" from my composer.json makes the errors disappear. It seems to be related to the above error or at least to some strange change in (empty) array-handling.

1. "Offset 2 does not exist on array\{\}"
2. Call to static method PHPUnit\\Framework\\Assert\:\:assertEmpty\(\) with array\{\} will always evaluate to true
3. Call to static method PHPUnit\\Framework\\Assert\:\:assertNotEmpty\(\) with ''\|'0' will always evaluate to false

I get error 1 with this code (don't know how to make this work in the playground https://phpstan.org/r/4c9d4805-10c1-46d3-9190-4546b87c7449) :
```
$users = $object->getUsers();
self::assertSame('email@example.com', $users[2]->getEmail());
```
while getUsers() clearly always return an array with User-objects.

Error 2 and 3 occur with this code:
```
self::assertEmpty(functionThatAlwaysReturnsAnEmptyArrayOrArrayOfObjects());
self::assertNotEmpty(functionThatAlwaysReturnsAnEmptyStringOrString());
```

**Comment by ondrejmirtes** [comment]
@Knallcharge Your issues are unrelated and most likely are result of old getUsers() value being remembered: https://phpstan.org/blog/remembering-and-forgetting-returned-values

**Comment by ondrejmirtes** [comment]
And your number 3 is expected I'd say.

**Comment by knallcharge** [comment]
@ondrejmirtes Thanks for getting back! You're probably right, I'll check out the link, I wasn't aware of remembered values.

About my number 3: As my function (as the function name suggests, but maybe I didn't name it clearly enough) always returns a string which can be an empty one, I'd expect `assertNotEmpty('')` to be false and `assertNotEmpty('text')` to be true ...

**Comment by ondrejmirtes** [comment]
But PHPStan thinks it's `''|'0'`. Maybe anothe case of remembered value.

**Comment by knallcharge** [comment]
Probably, thanks!

**Comment by ondrejmirtes** [comment]
Oh, it's caused by `treatPhpDocTypesAsCertain: false`, with `true` it doesn't report a false positive.

Hopefully after https://github.com/phpstan/phpstan/issues/8191 is done it will no longer be a problem, that's gonna clean up a lot of things.

**Comment by ondrejmirtes** [comment]
So what the result is with PHPStan 1.9.0? I have a suspicion it's gonna be fixed.

**Comment by Seldaek** [comment]
Yup, it's gone 🥳
