### ISSUE TITLE
After `Assert::assertIsList` variable is not a list

### ISSUE THREAD

**Issue by mitelg** [phpstan/phpstan-phpunit#212]
Hey there :wave: 

I recently found that, the assertion `\PHPUnit\Framework\Assert::assertIsList` is not handled correctly. The variable has the following type after this check `Dumped type: array<int, string>`. But it should be `Dumped type: list<string>` instead. 

If you would point me to the correct please, I could try to provide a fix. 

Best regards

**Comment by ondrejmirtes** [comment]
There's no code around assertIsList in this extension so PHPStan solely relies on the PHPDoc above the function which looks like this: https://github.com/sebastianbergmann/phpunit/blob/d81cfde3082807ab0db366c8424cb5bbbfcdc03b/src/Framework/Assert.php#L196-L206

So it does not provide any assert.

You could send a PR to PHPUnit so that this PHPDoc is added. Meanwhile it could be fixed by adding a stub in phpstan-phpunit.

**Comment by mitelg** [comment]
I am not sure, if I understand correctly, what needs to be done :see_no_evil: 

You mean only by adding a comment like `Asserts that an array is a list.` above the method is enough? :thinking: Other than that, I do not really see a difference to other methods

**Comment by ondrejmirtes** [comment]
You need to add `@phpstan-assert` PHPDoc tag above the method. PHPUnit has that already in many places.

**Comment by mitelg** [comment]
ah! :bulb: I was only looking at the methods around `assertIsList` and was wondering how this should work :sweat_smile: 

thanks, I will provide a fix for PHPUnit then :+1:
