### ISSUE TITLE
Requiring PHPUnit test cases to be autoloadable is excessive

### ISSUE THREAD

**Issue by kamazee** [phpstan/phpstan-phpunit#22]
When I analyze tests, phpstan produces a handful of errors such as
```
 ------ ------------------------------------------------------------------------------------------------------------------------------ 
  Line   lib/Library/test/SomeTest.php                                                                                              
 ------ ------------------------------------------------------------------------------------------------------------------------------ 
         Class MyPrefix\Library\SomeTest was not found while trying to analyse it - autoloading is probably not configured properly.  
 ------ ------------------------------------------------------------------------------------------------------------------------------
```

PHPUnit doesn't require an autoloader to load test cases (user-defined classes that extend `PHPUnit\Framework\TestCase` and contain actual test code), and (in my opinion) neither should phpstan. PHPUnit finds them by just traversing files and they don't really belong to autoloader because nobody but PHPUnit should use them, which is more or less prevented by making them non-autoloadable. This is only applicable to test cases, though (or, more precisely, classes that extend `PHPUnit\Framework\TestCase` and are only referenced from within themselves): any dependencies should, of course, be discoverable by autoloader.

@ondrejmirtes, what do you think?

**Comment by ondrejmirtes** [comment]
Hi, this is current limitation (or basically how it works) of PHPStan. It needs to autoload the classes. There's no disadvantage of putting `tests` directory into PHPStan's `autoload_directories` option or using Composer's `autoload-dev`. There's one unforeseen advantage - if you use the PSR-4 autoload convention, PHPStan will find classes with the wrong name/namespace/filename, or to be more precise, it does not find them 😊 So that's one thing to appreciate with the current way of doing things.

There are many other issues connected to this fact that PHPStan needs the autoloader - they are linked here: https://github.com/phpstan/phpstan/milestone/2

It will be solved by switching to static reflection, which is a major undertaking. I might have one trick up my sleeve that will possibly work with not that much work and might come quite soon, so stay tuned 😊
