### ISSUE TITLE
[Feature Request] Report error when trying to configure a non existing method on MockObject.

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-phpunit#71]
I would be nice if phpstan could return an error for
```
$foo = $this->createMock(Foo::class);
$foo->method('nonExistingMethod');
```

`$foo` is know as `Foo&MockObject` so I think this would be possible.

**Comment by VincentLanglet** [comment]
This would need a `InvocationMockerType`.
C.F. https://github.com/phpstan/phpstan-phpunit/issues/48#issuecomment-502084369

@ondrejmirtes I'll be happy to write the rule, I think I can (thanks to TDD). [I have already wrote another rule](https://github.com/phpstan/phpstan-phpunit/pull/69). But I have more difficulties to see what I should I write in the `InvocationMockerType` and how to use it. Could you help me ?

**Comment by ondrejmirtes** [comment]
`$foo->method('nonExistingMethod')` is called on `MockObject&Foo` in your case. So writing the rule is easy, you can start by registering a rule for `MethodCall`, see that `$scope->getType($methodCall->var)` is an IntersectionType of `MockObject` and the other type, get the other type and see if it `->hasMethod()` that's in the string.

To also understand `$foo->expects(...)->method('nonExistingMethod')`, we'd have to probably make `InvocationMocker` generic (using a stub file) and write a dynamic return type extension so that `->expects` on `MockObject&T` returns `InvocationMocker<T>`. We'd then be able to write a similar rule to the one described in the first paragraph.

**Comment by VincentLanglet** [comment]
@ondrejmirtes stubs seems to not be used when I run tests.

I get 
```
object(PHPStan\Type\ObjectType)#8114 (4) {
  ["className":"PHPStan\Type\ObjectType":private]=>
  string(39) "PHPUnit\Framework\MockObject\MockObject"
  ["subtractedType":"PHPStan\Type\ObjectType":private]=>
  NULL
  ["genericObjectType":"PHPStan\Type\ObjectType":private]=>
  NULL
  ["superTypes":"PHPStan\Type\ObjectType":private]=>
  array(0) {
  }
}
```
instead of an IntersectionType.

If I modify the phpDoc of the phpunit-vendor, I get an IntersectionType.

Do you know how to fix this ?

**Comment by ondrejmirtes** [comment]
Can you open a draft PR so I can look at it more closely?

**Comment by VincentLanglet** [comment]
Sure @ondrejmirtes : https://github.com/phpstan/phpstan-phpunit/pull/72/files

I expect, `var_dump($type)` to return an `IntersectionType`
