### ISSUE TITLE
phph 7.4 typed hinted properties and mocks

### ISSUE THREAD

**Issue by nikophil** [phpstan/phpstan-phpunit#75]
Hello,

here is a problematic snippet in php 7.4:
```php
<?php

class MyTest extends TestCase

    private Object $testedObject
    private $someMockedObject;

    public function setUp(): void
    {
         $this->testedObject = new Object();
         $this->someMockedObject = $this->createMock(SomeInterface::class);
    }

    public function testItDoesSomething(): void
    {
        $this->someMockedObject->expects()...

        $this->testedObject->doSomething($this->someMockedObject);
    }
```

First, at level 6, phpstan complains about the property which has no typehint
```
Property MyTest::$someMockedObject has no typehint specified
```

Event if we put `/* @var SomeInterface|MockObject */` it still complains.

Thus, we have to chose a type hint between `MockObject` or `SomeInterface` but it complains one way like the other because `expects()` method is unknown on `SomeInterface` or `Object::doSomething()` parameter 1 expects an instance of `SomeInterface`

any clue how i can make this pass?

thanks :)

**Comment by ondrejmirtes** [comment]
Hi, make sure to read the docs: https://phpstan.org/writing-php-code/phpdocs-basics

What I want you to learn is:

> Valid PHPDocs start with `/**`. Variants starting only with `/*` or line comments `//` are not considered PHPDocs.

Also read about union vs. intersection types (https://phpstan.org/blog/union-types-vs-intersection-types). You want `SomeInterface&MockObject`, not `SomeInterface|MockObject`, although phpstan-phpunit makes your life a bit easier because it automatically considers `SomeInterface|MockObject` an intersection type even if it's academically wrong.

**Comment by nikophil** [comment]
thanks for your answer, i've just figured this out after asking the question
